.TH "Fusion::Internal" 3 "Thu Apr 30 2015" "fusion" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fusion::Internal \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBbuffer_t\fP * \fBdivBuffer\fP (\fBbuffer_t\fP *buf, int start, int nend)"
.br
.ti -1c
.RI "uint8_t * \fBinitBuffer_t\fP (int x, int y, int z, int w, \fBbuffer_t\fP *buf, int bitOfInput)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBbuffer_t\fP* Fusion::Internal::divBuffer (\fBbuffer_t\fP *buf, intstart, intnend)"

.SS "uint8_t* Fusion::Internal::initBuffer_t (intx, inty, intz, intw, \fBbuffer_t\fP *buf, intbitOfInput)"

.SH "Author"
.PP 
Generated automatically by Doxygen for fusion from the source code\&.
