.TH "Fusion::Dynamic" 3 "Thu Apr 30 2015" "fusion" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fusion::Dynamic \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDynamicDispatch\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename\&.\&.\&. Args> void \fBworkThread\fP (Args\&.\&.\&.args, function< int(Args\&.\&.\&., \fBbuffer_t\fP *, \fBbuffer_t\fP *)> func, \fBbuffer_t\fP *input, \fBbuffer_t\fP *output, \fBstatus\fP table[], int offset, mutex *table_mutex)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "template<typename\&.\&.\&. Args> void Fusion::Dynamic::workThread (Args\&.\&.\&.args, function< int(Args\&.\&.\&., \fBbuffer_t\fP *, \fBbuffer_t\fP *)>func, \fBbuffer_t\fP *input, \fBbuffer_t\fP *output, \fBstatus\fPtable[], intoffset, mutex *table_mutex)"
TODO:find out a way to interrupt cpu work thread 
.SH "Author"
.PP 
Generated automatically by Doxygen for fusion from the source code\&.
