.TH "fusion_info.h" 3 "Thu Apr 30 2015" "fusion" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fusion_info.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBstatus\fP { \fBidle\fP =0, \fBcomputing\fP, \fBwriting\fP, \fBfinished\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBstatus\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIidle \fP\fP
.TP
\fB\fIcomputing \fP\fP
.TP
\fB\fIwriting \fP\fP
.TP
\fB\fIfinished \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for fusion from the source code\&.
