.TH "internal.h" 3 "Thu Apr 30 2015" "fusion" \" -*- nroff -*-
.ad l
.nh
.SH NAME
internal.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBbuffer_t\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBFusion\fP"
.br
.ti -1c
.RI "\fBFusion::Internal\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTOOL_H\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBbuffer_t\fP \fBbuffer_t\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBbuffer_t\fP * \fBFusion::Internal::divBuffer\fP (\fBbuffer_t\fP *buf, int start, int nend)"
.br
.ti -1c
.RI "uint8_t * \fBFusion::Internal::initBuffer_t\fP (int x, int y, int z, int w, \fBbuffer_t\fP *buf, int bitOfInput)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define TOOL_H"

.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBbuffer_t\fP  \fBbuffer_t\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for fusion from the source code\&.
